### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Vikas2201**

### CODE REVIEW

**Comment by Vikas2201** [comment]
vikas

**Comment by shubhamchau222** [comment]
will be merge tomorrow

**Review by shubhamchau222 — APPROVED** [review]
conflict

**Review by shubhamchau222 — APPROVED** [review]
approved

**Review by shubhamchau222 — APPROVED** [review]
approved

**Review by shubhamchau222 — APPROVED** [review]
approved

**Comment by shubhamchau222** [comment]
closed

**Pull request closed without merging**
